-- 코드를 작성해주세요
SELECT T1.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T1 JOIN ITEM_INFO I ON T1.ITEM_ID = I.ITEM_ID
WHERE T1.ITEM_ID NOT IN (SELECT DISTINCT T2.PARENT_ITEM_ID 
                         FROM ITEM_TREE T2
                         WHERE T2.PARENT_ITEM_ID IS NOT NULL)
ORDER BY T1.ITEM_ID DESC;