-- 코드를 입력하세요

WITH RECURSIVE t AS (SELECT 0 n UNION ALL SELECT n+1 FROM t WHERE n<23)
SELECT t.n AS hour, COUNT(a.animal_id)
FROM t LEFT JOIN ANIMAL_OUTS a ON HOUR(a.DATETIME)=t.n
GROUP BY t.n ORDER BY t.n;