-- 코드를 입력하세요
SELECT MEMBER_ID , MEMBER_NAME,GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH,'%M')='MARCH' AND TLNO is not null and gender='W'
order by MEMBER_id asc;