-- 코드를 작성해주세요
SELECT YEAR(E1.DIFFERENTIATION_DATE) AS YEAR, (T.MAXSIZE-E1.SIZE_OF_COLONY) YEAR_DEV, E1.ID AS ID
FROM ECOLI_DATA E1 JOIN (SELECT YEAR(DIFFERENTIATION_DATE) DD, MAX(SIZE_OF_COLONY) MAXSIZE
                        FROM ECOLI_DATA
                        GROUP BY DD) T ON YEAR(E1.DIFFERENTIATION_DATE) = T.DD
ORDER BY YEAR ASC, YEAR_DEV ASC;